import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import {
  Star, GitFork, Download, Users, GitCommitHorizontal,
  GitPullRequest, CircleDot, CheckCircle, XCircle, TrendingUp,
  Package, Clock, Award, Globe
} from 'lucide-react';
import { useSEO } from '../hooks/useSEO';
import { AreaChart, Area, XAxis, Tooltip, ResponsiveContainer } from 'recharts';

// ─────────────────────────────────────────────
// Mini bar chart rendered with pure CSS/HTML
// ─────────────────────────────────────────────
function TrendChart({ data }) {
  if (!data || data.length === 0) return null;
  
  return (
    <div style={{ width: '100%', height: '120px', marginTop: '16px' }}>
      <ResponsiveContainer width="100%" height="100%">
        <AreaChart data={data}>
          <defs>
            <linearGradient id="colorDownloads" x1="0" y1="0" x2="0" y2="1">
              <stop offset="5%" stopColor="var(--neon-green)" stopOpacity={0.4}/>
              <stop offset="95%" stopColor="var(--neon-green)" stopOpacity={0}/>
            </linearGradient>
          </defs>
          <XAxis 
            dataKey="day" 
            hide={true} 
          />
          <Tooltip 
            contentStyle={{ backgroundColor: 'var(--nav-bg)', border: '1px solid var(--neon-green)', borderRadius: '8px', color: 'var(--text-primary)' }}
            itemStyle={{ color: 'var(--neon-green)', fontWeight: 'bold' }}
            labelStyle={{ color: 'var(--text-secondary)', marginBottom: '4px' }}
            cursor={{ stroke: 'rgba(0, 255, 136, 0.2)', strokeWidth: 2 }}
          />
          <Area 
            type="monotone" 
            dataKey="downloads" 
            stroke="var(--neon-green)" 
            strokeWidth={2}
            fillOpacity={1} 
            fill="url(#colorDownloads)" 
            name="Downloads"
          />
        </AreaChart>
      </ResponsiveContainer>
    </div>
  );
}

// ─────────────────────────────────────────────
// Ecosystem Health Badge
// ─────────────────────────────────────────────
function EcosystemBadge({ name, registry, healthy, url }) {
  const { t } = useTranslation();
  return (
    <a
      href={url}
      target="_blank"
      rel="noreferrer"
      style={{ textDecoration: 'none', color: 'inherit' }}
    >
      <div className="glass-panel" style={{
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        padding: '16px 20px',
        borderLeft: `3px solid ${healthy ? 'var(--neon-green)' : 'var(--error-text)'}`,
        transition: 'transform 0.2s ease',
      }}
        onMouseEnter={e => e.currentTarget.style.transform = 'translateX(4px)'}
        onMouseLeave={e => e.currentTarget.style.transform = 'translateX(0)'}
      >
        <div>
          {healthy
            ? <CheckCircle size={20} color="var(--neon-green)" />
            : <XCircle size={20} color="#ff3366" />}
        </div>
        <div style={{ flex: 1 }}>
          <div style={{ fontWeight: 'bold', fontSize: '0.95rem' }}>{name}</div>
          <div style={{ color: 'var(--text-secondary)', fontSize: '0.8rem' }}>{registry}</div>
        </div>
        <div style={{
          fontSize: '0.75rem',
          padding: '3px 10px',
          borderRadius: '10px',
          background: healthy ? 'var(--success-bg)' : 'var(--error-bg)',
          color: healthy ? 'var(--neon-green)' : 'var(--error-text)',
          fontWeight: 'bold',
        }}>
          {healthy ? t('insights_page.online', 'ONLINE') : t('insights_page.down', 'DOWN')}
        </div>
      </div>
    </a>
  );
}

// ─────────────────────────────────────────────
// Main Insights Page
// ─────────────────────────────────────────────
export default function Insights() {
  const { t } = useTranslation();
  useSEO(
    'Insights',
    'Live download stats, GitHub activity, contributor metrics, and ecosystem health for moz-utils across NPM, PyPI, Packagist, and pub.dev.'
  );

  const [stats, setStats] = useState(null);
  const [liveGH, setLiveGH] = useState(null);
  const [loading, setLoading] = useState(true);

  // Load static stats.json (generated by GitHub Actions) with local fallback to prod
  // Also augment with REAL-TIME downloads from official registries!
  useEffect(() => {
    const fetchStats = async () => {
      try {
        let data = null;
        try {
          const res = await fetch('/stats.json');
          if (res.ok) data = await res.json();
        } catch (e) {}

        if (!data) {
          const res = await fetch('https://iradoweck.github.io/moz-utils/stats.json');
          if (res.ok) data = await res.json();
        }

        if (!data) data = { downloads: { ts: 0, php: 0, python: 0, dart: 0 }, ecosystem: {} };

        // Real-time fetching from Registries (NPM only, others use stats.json to avoid CORS)
        try {
          const npmRes = await fetch('https://api.npmjs.org/downloads/point/last-month/moz-utils').then(r => r.json());
          if (npmRes && npmRes.downloads) {
            data.downloads.ts = npmRes.downloads;
          }
        } catch (e) {
          console.warn('Failed to fetch live NPM stats', e);
        }

        setStats(data);
        setLoading(false);
      } catch (err) {
        setLoading(false);
      }
    };
    fetchStats();
  }, []);

  // Load live GitHub data (with fallback to stats.json if rate-limited) and Live NPM Trend Data
  useEffect(() => {
    const REPO = 'iradoweck/moz-utils';
    Promise.allSettled([
      fetch(`https://api.github.com/repos/${REPO}`),
      fetch(`https://api.github.com/repos/${REPO}/commits?per_page=5`),
      fetch(`https://api.npmjs.org/downloads/range/last-month/moz-utils`)
    ]).then(async ([repoRes, commitsRes, npmRes]) => {
      let repo = null;
      let commits = [];
      
      // Only use GitHub API data if response is 200 OK (avoids 403 Rate Limit or 404)
      if (repoRes.status === 'fulfilled' && repoRes.value.ok) {
        repo = await repoRes.value.json();
      }
      if (commitsRes.status === 'fulfilled' && commitsRes.value.ok) {
        commits = await commitsRes.value.json();
      }
      
      let liveNpmTrend = [];
      if (npmRes.status === 'fulfilled' && npmRes.value.ok) {
        const npmData = await npmRes.value.json();
        if (npmData && npmData.downloads) {
          liveNpmTrend = npmData.downloads;
        }
      }

      setLiveGH({ 
        repo, 
        commits: Array.isArray(commits) ? commits : (commits.items || []),
        issues: undefined,
        prs: undefined,
        npmTrend: liveNpmTrend
      });
    });
  }, []);

  const dl = stats?.downloads || {};
  const total = dl.total ?? ((dl.ts || 0) + (dl.php || 0) + (dl.python || 0) + (dl.dart || 0));
  const gh = liveGH?.repo || {};
  const contributors = stats?.contributors || [];
  const trend = (liveGH?.npmTrend && liveGH.npmTrend.length > 0) ? liveGH.npmTrend : (stats?.npm_trend || []);
  const ecosystem = stats?.ecosystem || {};
  const recentCommits = liveGH?.commits || stats?.recent_commits || [];

  // Compute most popular ecosystem
  const dlBreakdown = [
    { label: 'TypeScript / NPM', count: Number(dl.ts) || 0, color: '#3178c6' },
    { label: 'PHP / Packagist', count: Number(dl.php) || 0, color: '#8993be' },
    { label: 'Python / PyPI', count: Number(dl.python) || 0, color: '#f7c948' },
    { label: 'Dart / pub.dev', count: Number(dl.dart) || 0, color: '#00b4d8' },
  ].sort((a, b) => b.count - a.count);

  const topEcosystem = dlBreakdown[0];
  const topPercent = total > 0 && topEcosystem ? Math.round((topEcosystem.count / total) * 100) : 0;

  const getEcoUrl = (k) => {
    switch(k) {
      case 'npm': return 'https://www.npmjs.com/package/moz-utils';
      case 'pypi': return 'https://pypi.org/project/moz-utils/';
      case 'pub': return 'https://pub.dev/packages/moz_utils';
      case 'packagist': return 'https://packagist.org/packages/iradoweck/moz-utils';
      default: return '#';
    }
  };

  const ecoBadges = Object.entries(ecosystem).map(([key, val]) => ({
    ...val,
    url: getEcoUrl(key),
  }));

  return (
    <div className="container animate-fade-up" style={{ padding: '60px 20px' }}>

      {/* Page Header */}
      <div style={{ textAlign: 'center', marginBottom: '60px' }}>
        <h1 style={{ fontSize: '3rem', marginBottom: '16px' }}>{t('nav.insights')}</h1>
        <p style={{ color: 'var(--text-secondary)', fontSize: '1.2rem', maxWidth: '800px', margin: '0 auto' }}>
          {t('insights_page.description')}
        </p>
        {stats?.generated_at && (
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.8rem', marginTop: '12px', opacity: 0.6 }}>
            <Clock size={12} style={{ verticalAlign: 'middle', marginRight: '4px' }} />
            {t('insights_page.last_updated', 'Last updated:')} {new Date(stats.generated_at).toLocaleString()}
          </p>
        )}
      </div>

      {loading && (
        <p style={{ textAlign: 'center', color: 'var(--text-secondary)' }}>{t('insights_page.loading_insights')}</p>
      )}

      {/* ── Section 1: GitHub KPIs ── */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: '16px', marginBottom: '48px' }}>
        {(gh.stargazers_count >= 3 || gh.stargazers_count === undefined) && (
          <div className="glass-panel" style={{ textAlign: 'center' }}>
            <Star size={28} color="var(--neon-green)" style={{ margin: '0 auto 12px auto' }} />
            <h2 style={{ fontSize: '2rem', margin: '0' }}>{gh.stargazers_count ?? (stats?.github?.stars ?? '—')}</h2>
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem' }}>{t('insights_page.github_stars')}</p>
          </div>
        )}
        {(gh.forks_count >= 3 || gh.forks_count === undefined) && (
          <div className="glass-panel" style={{ textAlign: 'center' }}>
            <GitFork size={28} color="var(--neon-green)" style={{ margin: '0 auto 12px auto' }} />
            <h2 style={{ fontSize: '2rem', margin: '0' }}>{gh.forks_count ?? (stats?.github?.forks ?? '—')}</h2>
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem' }}>{t('insights_page.forks')}</p>
          </div>
        )}
        <div className="glass-panel" style={{ textAlign: 'center' }}>
          <CircleDot size={28} color="#ff9f0a" style={{ margin: '0 auto 12px auto' }} />
          <h2 style={{ fontSize: '2rem', margin: '0' }}>
            <span style={{ color: '#ff9f0a' }}>{liveGH?.issues?.open ?? (stats?.github?.open_issues ?? 0)}</span>
            <span style={{ color: 'var(--text-secondary)', fontSize: '1.2rem', margin: '0 4px' }}>/</span>
            <span style={{ color: 'var(--text-secondary)' }}>{liveGH?.issues?.closed || (stats?.github?.closed_issues ?? 0)}</span>
          </h2>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem', marginTop: '4px' }}>{t('insights_page.open_closed_issues')}</p>
        </div>

        <div className="glass-panel" style={{ textAlign: 'center' }}>
          <GitPullRequest size={28} color="#bf5af2" style={{ margin: '0 auto 12px auto' }} />
          <h2 style={{ fontSize: '2rem', margin: '0' }}>
            <span style={{ color: '#bf5af2' }}>{liveGH?.prs?.open ?? (stats?.github?.open_prs ?? 0)}</span>
            <span style={{ color: 'var(--text-secondary)', fontSize: '1.2rem', margin: '0 4px' }}>/</span>
            <span style={{ color: 'var(--neon-green)' }}>{liveGH?.prs?.merged || (stats?.github?.merged_prs ?? 0)}</span>
          </h2>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem', marginTop: '4px' }}>{t('insights_page.open_merged_prs')}</p>
        </div>
        <div className="glass-panel" style={{ textAlign: 'center' }}>
          <Download size={28} color="var(--neon-green)" style={{ margin: '0 auto 12px auto' }} />
          <h2 style={{ fontSize: '2rem', margin: '0' }}>{total.toLocaleString()}</h2>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem' }}>{t('insights_page.total_downloads')}</p>
        </div>
      </div>

      {/* ── Section 2: Downloads per Ecosystem + Popularity ── */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px', marginBottom: '48px' }}>
        {/* Downloads breakdown */}
        <div className="glass-panel">
          <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '20px' }}>
            <Package size={20} color="var(--neon-green)" /> {t('insights_page.downloads_by_ecosystem')}
          </h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            {dlBreakdown.map(({ label, count, color }) => {
              const pct = total > 0 ? (count / total) * 100 : 0;
              return (
                <div key={label}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '4px', fontSize: '0.85rem' }}>
                    <span style={{ color: 'var(--text-secondary)' }}>{label}</span>
                    <span style={{ fontWeight: 'bold' }}>{count.toLocaleString()}</span>
                  </div>
                  <div style={{ height: '8px', background: 'var(--overlay-hover)', borderRadius: '4px', overflow: 'hidden' }}>
                    <div style={{ width: `${pct}%`, height: '100%', background: color, borderRadius: '4px', transition: 'width 1s ease' }} />
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Top Ecosystem + Trend */}
        <div className="glass-panel">
          <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '16px' }}>
            <TrendingUp size={20} color="var(--neon-green)" /> {t('insights_page.npm_weekly_trend')}
          </h3>
          {trend.length > 0 ? (
            <>
              <TrendChart data={trend} />
              <p style={{ color: 'var(--text-secondary)', fontSize: '0.75rem', marginTop: '8px', textAlign: 'center' }}>
                {t('insights_page.last_8_weeks', 'Last 8 weeks of NPM downloads')}
              </p>
            </>
          ) : (
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem' }}>{t('insights_page.no_trend_data')}</p>
          )}
          {topEcosystem && topEcosystem.count > 0 && (
            <div style={{
              marginTop: '16px',
              padding: '12px 16px',
              background: 'var(--success-bg)',
              borderRadius: '8px',
              borderLeft: '3px solid var(--neon-green)'
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <Award size={16} color="var(--neon-green)" />
                <span style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
                  <strong style={{ color: 'var(--neon-green)' }}>{topEcosystem.label}</strong> {t('insights_page.leads_with')} {topPercent}% {t('insights_page.of_all_downloads')}
                </span>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* ── Section 2.5: Removed Live Global Downloads Map ── */}

      {/* ── Section 3: Ecosystem Health ── */}
      {ecoBadges.length > 0 && (
        <div style={{ marginBottom: '48px' }}>
          <h2 style={{ fontSize: '1.5rem', marginBottom: '20px', display: 'flex', alignItems: 'center', gap: '12px' }}>
            <Globe color="var(--neon-green)" size={22} /> {t('insights_page.ecosystem_health')}
          </h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '12px' }}>
            {ecoBadges.map((b, i) => (
              <EcosystemBadge key={i} name={b.name} registry={b.registry} healthy={b.healthy} url={b.url} />
            ))}
          </div>
        </div>
      )}

      {/* ── Section 4: Recent Activity ── */}
      {recentCommits.length > 0 && (
        <div style={{ marginBottom: '48px' }}>
          <h2 style={{ fontSize: '1.5rem', marginBottom: '20px', display: 'flex', alignItems: 'center', gap: '12px' }}>
            <GitCommitHorizontal color="var(--neon-green)" size={22} /> {t('insights_page.recent_activity')}
          </h2>
          <div className="glass-panel" style={{ padding: '0' }}>
            {recentCommits.map((c, i) => {
              const sha = typeof c.sha === 'string' ? c.sha.substring(0, 7) : '';
              const msg = c.message || (c.commit?.message?.split('\n')[0]);
              
              // Handle author which can be an object in live API or string in stats.json
              let authorName = t('insights_page.unknown', 'Unknown');
              if (c.commit?.author?.name) {
                authorName = c.commit.author.name;
              } else if (typeof c.author === 'string') {
                authorName = c.author;
              } else if (c.author?.login) {
                authorName = c.author.login;
              }

              const date = c.date || c.commit?.author?.date;
              return (
                <div key={i} style={{
                  display: 'flex',
                  alignItems: 'flex-start',
                  gap: '16px',
                  padding: '16px 20px',
                  borderBottom: i < recentCommits.length - 1 ? '1px solid var(--panel-border)' : 'none',
                }}>
                  <GitCommitHorizontal size={16} color="var(--neon-green)" style={{ marginTop: '3px', flexShrink: 0 }} />
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <p style={{ margin: '0 0 4px 0', fontSize: '0.9rem', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                      {msg}
                    </p>
                    <p style={{ margin: 0, color: 'var(--text-secondary)', fontSize: '0.75rem' }}>
                      {authorName} · {date ? new Date(date).toLocaleDateString() : ''}
                    </p>
                  </div>
                  <code style={{
                    fontSize: '0.75rem',
                    color: 'var(--neon-green)',
                    background: 'var(--success-bg)',
                    padding: '2px 8px',
                    borderRadius: '4px',
                    flexShrink: 0
                  }}>
                    {sha}
                  </code>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* ── Section 5: Top Contributors (only if 2+ humans) ── */}
      {contributors.length >= 2 ? (
        <div style={{ marginTop: '48px' }}>
          <h2 style={{ fontSize: '1.5rem', marginBottom: '24px', display: 'flex', alignItems: 'center', gap: '12px' }}>
            <Users color="var(--neon-green)" size={22} /> {t('insights_page.top_contributors')}
          </h2>
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
            gap: '16px'
          }}>
            {contributors.map((c, idx) => (
              <div key={idx} className="glass-panel" style={{
                textAlign: 'center',
                padding: '24px 12px',
                backgroundColor: idx % 2 === 0 ? 'var(--success-bg)' : 'var(--overlay-1)'
              }}>
                <img
                  src={c.avatar}
                  alt={c.login}
                  style={{ width: '64px', height: '64px', borderRadius: '50%', marginBottom: '12px', border: '2px solid var(--neon-green)' }}
                />
                <h4 style={{ margin: '0 0 8px 0', fontSize: '1rem', wordBreak: 'break-all' }}>@{c.login}</h4>
                {['iradoweck', 'zedeckmuacy'].includes(c.login.toLowerCase()) ? (
                  <span style={{
                    background: 'var(--warning-bg)',
                    padding: '4px 12px',
                    borderRadius: '12px',
                    fontSize: '0.8rem',
                    color: '#FFD700',
                    fontWeight: 'bold'
                  }}>
                    {t('insights_page.creator_maintainer')}
                  </span>
                ) : (
                  <span style={{
                    background: 'var(--overlay-3)',
                    padding: '4px 12px',
                    borderRadius: '12px',
                    fontSize: '0.8rem',
                    color: 'var(--neon-green)'
                  }}>
                    {c.contributions} {t('insights_page.commits')}
                  </span>
                )}
              </div>
            ))}
          </div>
        </div>
      ) : (
        <div className="glass-panel" style={{
          textAlign: 'center',
          padding: '48px 32px',
          borderStyle: 'dashed',
          borderColor: 'var(--panel-border)',
          marginTop: '48px'
        }}>
          <Users size={48} color="var(--neon-green)" style={{ margin: '0 auto 20px auto', opacity: 0.6 }} />
          <h3 style={{ marginBottom: '12px' }}>{t('insights_page.want_to_contribute')}</h3>
          <p style={{ color: 'var(--text-secondary)', maxWidth: '500px', margin: '0 auto 24px auto' }}>
            {t('insights_page.contribute_desc')}
          </p>
          <a
            href="https://github.com/iradoweck/moz-utils/blob/main/CONTRIBUTING.md"
            target="_blank"
            rel="noreferrer"
            className="btn-primary"
          >
            {t('insights_page.read_contrib_guide')}
          </a>
        </div>
      )}
    </div>
  );
}
