import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import {
  BarChart3, Star, GitFork, Download, Users, GitCommitHorizontal,
  GitPullRequest, CircleDot, CheckCircle, XCircle, TrendingUp,
  Package, Clock, Award, Globe
} from 'lucide-react';
import { useSEO } from '../hooks/useSEO';

// ─────────────────────────────────────────────
// Mini bar chart rendered with pure CSS/HTML
// ─────────────────────────────────────────────
function TrendChart({ data }) {
  if (!data || data.length === 0) return null;
  const max = Math.max(...data.map(d => d.count), 1);
  return (
    <div style={{ display: 'flex', alignItems: 'flex-end', gap: '4px', height: '60px', padding: '0 4px' }}>
      {data.map((d, i) => {
        const height = Math.max((d.count / max) * 100, 4);
        return (
          <div
            key={i}
            title={`Week of ${d.week}: ${d.count} downloads`}
            style={{
              flex: 1,
              height: `${height}%`,
              background: `rgba(0, 255, 136, ${0.3 + (height / 100) * 0.7})`,
              borderRadius: '3px 3px 0 0',
              transition: 'all 0.3s ease',
              cursor: 'default',
            }}
          />
        );
      })}
    </div>
  );
}

// ─────────────────────────────────────────────
// Ecosystem Health Badge
// ─────────────────────────────────────────────
function EcosystemBadge({ name, registry, healthy, url }) {
  return (
    <a
      href={url}
      target="_blank"
      rel="noreferrer"
      style={{ textDecoration: 'none', color: 'inherit' }}
    >
      <div className="glass-panel" style={{
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        padding: '16px 20px',
        borderLeft: `3px solid ${healthy ? 'var(--neon-green)' : '#ff3366'}`,
        transition: 'transform 0.2s ease',
      }}
        onMouseEnter={e => e.currentTarget.style.transform = 'translateX(4px)'}
        onMouseLeave={e => e.currentTarget.style.transform = 'translateX(0)'}
      >
        <div>
          {healthy
            ? <CheckCircle size={20} color="var(--neon-green)" />
            : <XCircle size={20} color="#ff3366" />}
        </div>
        <div style={{ flex: 1 }}>
          <div style={{ fontWeight: 'bold', fontSize: '0.95rem' }}>{name}</div>
          <div style={{ color: 'var(--text-secondary)', fontSize: '0.8rem' }}>{registry}</div>
        </div>
        <div style={{
          fontSize: '0.75rem',
          padding: '3px 10px',
          borderRadius: '10px',
          background: healthy ? 'rgba(0,255,136,0.15)' : 'rgba(255,51,102,0.15)',
          color: healthy ? 'var(--neon-green)' : '#ff3366',
          fontWeight: 'bold',
        }}>
          {healthy ? 'ONLINE' : 'DOWN'}
        </div>
      </div>
    </a>
  );
}

// ─────────────────────────────────────────────
// Main Insights Page
// ─────────────────────────────────────────────
export default function Insights() {
  const { t } = useTranslation();
  useSEO(
    'Insights',
    'Live download stats, GitHub activity, contributor metrics, and ecosystem health for moz-utils across NPM, PyPI, Packagist, and pub.dev.'
  );

  const [stats, setStats] = useState(null);
  const [liveGH, setLiveGH] = useState(null);
  const [loading, setLoading] = useState(true);

  // Load static stats.json (generated by GitHub Actions)
  useEffect(() => {
    fetch('/stats.json')
      .then(r => r.ok ? r.json() : null)
      .then(data => {
        setStats(data);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  // Load live GitHub data (CORS-safe: public API)
  useEffect(() => {
    const REPO = 'iradoweck/moz-utils';
    Promise.allSettled([
      fetch(`https://api.github.com/repos/${REPO}`),
      fetch(`https://api.github.com/repos/${REPO}/commits?per_page=5`),
    ]).then(async ([repoRes, commitsRes]) => {
      const repo = repoRes.status === 'fulfilled' && repoRes.value.ok ? await repoRes.value.json() : null;
      const commits = commitsRes.status === 'fulfilled' && commitsRes.value.ok ? await commitsRes.value.json() : [];
      setLiveGH({ repo, commits: Array.isArray(commits) ? commits : [] });
    });
  }, []);

  const dl = stats?.downloads || {};
  const total = dl.total ?? ((dl.ts || 0) + (dl.php || 0) + (dl.python || 0) + (dl.dart || 0));
  const gh = liveGH?.repo || {};
  const contributors = stats?.contributors || [];
  const trend = stats?.npm_trend || [];
  const ecosystem = stats?.ecosystem || {};
  const recentCommits = liveGH?.commits || stats?.recent_commits || [];

  // Compute most popular ecosystem
  const dlBreakdown = [
    { label: 'TypeScript / NPM', count: Number(dl.ts) || 0, color: '#3178c6' },
    { label: 'PHP / Packagist', count: Number(dl.php) || 0, color: '#8993be' },
    { label: 'Python / PyPI', count: Number(dl.python) || 0, color: '#f7c948' },
    { label: 'Dart / pub.dev', count: Number(dl.dart) || 0, color: '#00b4d8' },
  ].sort((a, b) => b.count - a.count);

  const topEcosystem = dlBreakdown[0];
  const topPercent = total > 0 && topEcosystem ? Math.round((topEcosystem.count / total) * 100) : 0;

  const ecoBadges = Object.entries(ecosystem).map(([key, val]) => ({
    ...val,
    url: {
      npm: 'https://www.npmjs.com/package/moz-utils',
      pypi: 'https://pypi.org/project/moz-utils/',
      pub: 'https://pub.dev/packages/moz_utils',
      packagist: 'https://packagist.org/packages/iradoweck/moz-utils',
    }[key] || '#',
  }));

  return (
    <div className="container animate-fade-up" style={{ padding: '60px 20px' }}>

      {/* Page Header */}
      <div style={{ textAlign: 'center', marginBottom: '60px' }}>
        <h1 style={{ fontSize: '3rem', marginBottom: '16px' }}>{t('nav.insights')}</h1>
        <p style={{ color: 'var(--text-secondary)', fontSize: '1.2rem', maxWidth: '800px', margin: '0 auto' }}>
          {t('insights_page.description')}
        </p>
        {stats?.generated_at && (
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.8rem', marginTop: '12px', opacity: 0.6 }}>
            <Clock size={12} style={{ verticalAlign: 'middle', marginRight: '4px' }} />
            Last updated: {new Date(stats.generated_at).toLocaleString()}
          </p>
        )}
      </div>

      {loading && (
        <p style={{ textAlign: 'center', color: 'var(--text-secondary)' }}>Loading insights data…</p>
      )}

      {/* ── Section 1: GitHub KPIs ── */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))', gap: '16px', marginBottom: '48px' }}>
        {(gh.stargazers_count >= 3 || gh.stargazers_count === undefined) && (
          <div className="glass-panel" style={{ textAlign: 'center' }}>
            <Star size={28} color="var(--neon-green)" style={{ margin: '0 auto 12px auto' }} />
            <h2 style={{ fontSize: '2rem', margin: '0' }}>{gh.stargazers_count ?? (stats?.github?.stars ?? '—')}</h2>
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem' }}>GitHub Stars</p>
          </div>
        )}
        {(gh.forks_count >= 3 || gh.forks_count === undefined) && (
          <div className="glass-panel" style={{ textAlign: 'center' }}>
            <GitFork size={28} color="var(--neon-green)" style={{ margin: '0 auto 12px auto' }} />
            <h2 style={{ fontSize: '2rem', margin: '0' }}>{gh.forks_count ?? (stats?.github?.forks ?? '—')}</h2>
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem' }}>Forks</p>
          </div>
        )}
        <div className="glass-panel" style={{ textAlign: 'center' }}>
          <CircleDot size={28} color="#ff9f0a" style={{ margin: '0 auto 12px auto' }} />
          <h2 style={{ fontSize: '2rem', margin: '0' }}>{gh.open_issues_count ?? (stats?.github?.open_issues ?? '—')}</h2>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem' }}>Open Issues</p>
        </div>
        <div className="glass-panel" style={{ textAlign: 'center' }}>
          <GitPullRequest size={28} color="#bf5af2" style={{ margin: '0 auto 12px auto' }} />
          <h2 style={{ fontSize: '2rem', margin: '0' }}>{stats?.github?.open_prs ?? '—'}</h2>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem' }}>Open PRs</p>
        </div>
        <div className="glass-panel" style={{ textAlign: 'center' }}>
          <Download size={28} color="var(--neon-green)" style={{ margin: '0 auto 12px auto' }} />
          <h2 style={{ fontSize: '2rem', margin: '0' }}>{total.toLocaleString()}</h2>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem' }}>Total Downloads</p>
        </div>
      </div>

      {/* ── Section 2: Downloads per Ecosystem + Popularity ── */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px', marginBottom: '48px' }}>
        {/* Downloads breakdown */}
        <div className="glass-panel">
          <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '20px' }}>
            <Package size={20} color="var(--neon-green)" /> Downloads by Ecosystem
          </h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
            {dlBreakdown.map(({ label, count, color }) => {
              const pct = total > 0 ? (count / total) * 100 : 0;
              return (
                <div key={label}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '4px', fontSize: '0.85rem' }}>
                    <span style={{ color: 'var(--text-secondary)' }}>{label}</span>
                    <span style={{ fontWeight: 'bold' }}>{count.toLocaleString()}</span>
                  </div>
                  <div style={{ height: '8px', background: 'rgba(255,255,255,0.08)', borderRadius: '4px', overflow: 'hidden' }}>
                    <div style={{ width: `${pct}%`, height: '100%', background: color, borderRadius: '4px', transition: 'width 1s ease' }} />
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Top Ecosystem + Trend */}
        <div className="glass-panel">
          <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '16px' }}>
            <TrendingUp size={20} color="var(--neon-green)" /> NPM Weekly Trend
          </h3>
          {trend.length > 0 ? (
            <>
              <TrendChart data={trend} />
              <p style={{ color: 'var(--text-secondary)', fontSize: '0.75rem', marginTop: '8px', textAlign: 'center' }}>
                Last 8 weeks of NPM downloads
              </p>
            </>
          ) : (
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem' }}>No trend data available yet.</p>
          )}
          {topEcosystem && topEcosystem.count > 0 && (
            <div style={{
              marginTop: '16px',
              padding: '12px 16px',
              background: 'rgba(0,255,136,0.05)',
              borderRadius: '8px',
              borderLeft: '3px solid var(--neon-green)'
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <Award size={16} color="var(--neon-green)" />
                <span style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
                  <strong style={{ color: 'var(--neon-green)' }}>{topEcosystem.label}</strong> leads with {topPercent}% of all downloads
                </span>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* ── Section 3: Ecosystem Health ── */}
      {ecoBadges.length > 0 && (
        <div style={{ marginBottom: '48px' }}>
          <h2 style={{ fontSize: '1.5rem', marginBottom: '20px', display: 'flex', alignItems: 'center', gap: '12px' }}>
            <Globe color="var(--neon-green)" size={22} /> Ecosystem Health
          </h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: '12px' }}>
            {ecoBadges.map((b, i) => (
              <EcosystemBadge key={i} {...b} />
            ))}
          </div>
        </div>
      )}

      {/* ── Section 4: Recent Activity ── */}
      {recentCommits.length > 0 && (
        <div style={{ marginBottom: '48px' }}>
          <h2 style={{ fontSize: '1.5rem', marginBottom: '20px', display: 'flex', alignItems: 'center', gap: '12px' }}>
            <GitCommitHorizontal color="var(--neon-green)" size={22} /> Recent Activity
          </h2>
          <div className="glass-panel" style={{ padding: '0' }}>
            {recentCommits.map((c, i) => {
              const sha = c.sha || c.sha?.substring(0, 7);
              const msg = c.message || (c.commit?.message?.split('\n')[0]);
              const author = c.author || c.commit?.author?.name;
              const date = c.date || c.commit?.author?.date;
              return (
                <div key={i} style={{
                  display: 'flex',
                  alignItems: 'flex-start',
                  gap: '16px',
                  padding: '16px 20px',
                  borderBottom: i < recentCommits.length - 1 ? '1px solid var(--panel-border)' : 'none',
                }}>
                  <GitCommitHorizontal size={16} color="var(--neon-green)" style={{ marginTop: '3px', flexShrink: 0 }} />
                  <div style={{ flex: 1, minWidth: 0 }}>
                    <p style={{ margin: '0 0 4px 0', fontSize: '0.9rem', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                      {msg}
                    </p>
                    <p style={{ margin: 0, color: 'var(--text-secondary)', fontSize: '0.75rem' }}>
                      {author} · {date ? new Date(date).toLocaleDateString() : ''}
                    </p>
                  </div>
                  <code style={{
                    fontSize: '0.75rem',
                    color: 'var(--neon-green)',
                    background: 'rgba(0,255,136,0.1)',
                    padding: '2px 8px',
                    borderRadius: '4px',
                    flexShrink: 0
                  }}>
                    {typeof sha === 'string' ? sha.substring(0, 7) : sha}
                  </code>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* ── Section 5: Top Contributors (only if 2+ humans) ── */}
      {contributors.length >= 2 ? (
        <div style={{ marginTop: '48px' }}>
          <h2 style={{ fontSize: '1.5rem', marginBottom: '24px', display: 'flex', alignItems: 'center', gap: '12px' }}>
            <Users color="var(--neon-green)" size={22} /> {t('insights_page.top_contributors')}
          </h2>
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
            gap: '16px'
          }}>
            {contributors.map((c, idx) => (
              <div key={idx} className="glass-panel" style={{
                textAlign: 'center',
                padding: '24px 12px',
                backgroundColor: idx % 2 === 0 ? 'rgba(0,255,136,0.05)' : 'rgba(255,255,255,0.02)'
              }}>
                <img
                  src={c.avatar}
                  alt={c.login}
                  style={{ width: '64px', height: '64px', borderRadius: '50%', marginBottom: '12px', border: '2px solid var(--neon-green)' }}
                />
                <h4 style={{ margin: '0 0 8px 0', fontSize: '1rem', wordBreak: 'break-all' }}>@{c.login}</h4>
                {['iradoweck', 'zedeckmuacy'].includes(c.login.toLowerCase()) ? (
                  <span style={{
                    background: 'rgba(255,215,0,0.2)',
                    padding: '4px 12px',
                    borderRadius: '12px',
                    fontSize: '0.8rem',
                    color: '#FFD700',
                    fontWeight: 'bold'
                  }}>
                    {t('insights_page.creator_maintainer')}
                  </span>
                ) : (
                  <span style={{
                    background: 'rgba(0,0,0,0.5)',
                    padding: '4px 12px',
                    borderRadius: '12px',
                    fontSize: '0.8rem',
                    color: 'var(--neon-green)'
                  }}>
                    {c.contributions} {t('insights_page.commits')}
                  </span>
                )}
              </div>
            ))}
          </div>
        </div>
      ) : (
        <div className="glass-panel" style={{
          textAlign: 'center',
          padding: '48px 32px',
          borderStyle: 'dashed',
          borderColor: 'var(--panel-border)',
          marginTop: '48px'
        }}>
          <Users size={48} color="var(--neon-green)" style={{ margin: '0 auto 20px auto', opacity: 0.6 }} />
          <h3 style={{ marginBottom: '12px' }}>Want to become a contributor?</h3>
          <p style={{ color: 'var(--text-secondary)', maxWidth: '500px', margin: '0 auto 24px auto' }}>
            This section will display contributors once the community starts growing. Be the first to contribute and have your name featured here!
          </p>
          <a
            href="https://github.com/iradoweck/moz-utils/blob/main/CONTRIBUTING.md"
            target="_blank"
            rel="noreferrer"
            className="btn-primary"
          >
            Read the Contribution Guide
          </a>
        </div>
      )}
    </div>
  );
}
