import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { BarChart3, Star, GitFork, Download, Users } from 'lucide-react';

export default function Insights() {
  const { t } = useTranslation();
  const [stats, setStats] = useState({
    downloads: { ts: '...', php: '...', python: '...', dart: '...' },
    github: { stars: '...', forks: '...' },
    contributors: []
  });

  useEffect(() => {
    // Attempt to load stats.json generated by our GitHub Action
    fetch(import.meta.env.BASE_URL + 'stats.json')
      .then(res => res.json())
      .then(data => setStats(data))
      .catch(err => {
        console.warn('Could not load stats.json, using fallback data.', err);
        // Fallback data for preview
        setStats({
          downloads: { ts: '1.2k', php: '800', python: '450', dart: '300' },
          github: { stars: '124', forks: '32' },
          contributors: [
            { login: 'iradoweck', avatar: 'https://avatars.githubusercontent.com/u/1?v=4', contributions: 150 },
            { login: 'contributor2', avatar: 'https://avatars.githubusercontent.com/u/2?v=4', contributions: 45 },
            { login: 'contributor3', avatar: 'https://avatars.githubusercontent.com/u/3?v=4', contributions: 22 },
            { login: 'contributor4', avatar: 'https://avatars.githubusercontent.com/u/4?v=4', contributions: 12 },
          ]
        });
      });
  }, []);

  return (
    <div className="container animate-fade-up" style={{ padding: '60px 20px' }}>
      <div style={{ textAlign: 'center', marginBottom: '60px' }}>
        <h1 style={{ fontSize: '3rem', marginBottom: '16px' }}>{t('nav.insights')}</h1>
        <p style={{ color: 'var(--text-secondary)', fontSize: '1.2rem', maxWidth: '800px', margin: '0 auto' }}>
          Estatísticas de uso em tempo real, transferências e o nosso ranking de contribuidores.
        </p>
      </div>

      {/* Estatísticas Gerais */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '20px', marginBottom: '40px' }}>
        <div className="glass-panel" style={{ textAlign: 'center' }}>
          <Star size={32} color="var(--neon-green)" style={{ margin: '0 auto 16px auto' }} />
          <h2 style={{ fontSize: '2.5rem', margin: '0' }}>{stats.github.stars}</h2>
          <p style={{ color: 'var(--text-secondary)' }}>GitHub Stars</p>
        </div>
        <div className="glass-panel" style={{ textAlign: 'center' }}>
          <GitFork size={32} color="var(--neon-green)" style={{ margin: '0 auto 16px auto' }} />
          <h2 style={{ fontSize: '2.5rem', margin: '0' }}>{stats.github.forks}</h2>
          <p style={{ color: 'var(--text-secondary)' }}>Forks</p>
        </div>
        <div className="glass-panel" style={{ textAlign: 'center' }}>
          <Download size={32} color="var(--neon-green)" style={{ margin: '0 auto 16px auto' }} />
          <h2 style={{ fontSize: '2.5rem', margin: '0' }}>{stats.downloads.ts}</h2>
          <p style={{ color: 'var(--text-secondary)' }}>Downloads NPM</p>
        </div>
        <div className="glass-panel" style={{ textAlign: 'center' }}>
          <BarChart3 size={32} color="var(--neon-green)" style={{ margin: '0 auto 16px auto' }} />
          <h2 style={{ fontSize: '2.5rem', margin: '0' }}>{stats.downloads.php}</h2>
          <p style={{ color: 'var(--text-secondary)' }}>Downloads Packagist</p>
        </div>
      </div>

      {/* Top Contribuidores (Formato Xadrez) */}
      <div style={{ marginTop: '60px' }}>
        <h2 style={{ fontSize: '2rem', marginBottom: '24px', display: 'flex', alignItems: 'center', gap: '12px' }}>
          <Users color="var(--neon-green)" /> Top Contribuidores
        </h2>
        <div style={{ 
          display: 'grid', 
          gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))', 
          gap: '16px' 
        }}>
          {stats.contributors.length > 0 ? stats.contributors.map((c, idx) => (
            <div key={idx} className="glass-panel" style={{ 
              textAlign: 'center', 
              padding: '24px 12px',
              backgroundColor: idx % 2 === 0 ? 'rgba(0,255,136,0.05)' : 'rgba(255,255,255,0.02)'
            }}>
              <img 
                src={c.avatar} 
                alt={c.login} 
                style={{ width: '64px', height: '64px', borderRadius: '50%', marginBottom: '12px', border: '2px solid var(--neon-green)' }} 
              />
              <h4 style={{ margin: '0 0 8px 0', fontSize: '1rem', wordBreak: 'break-all' }}>@{c.login}</h4>
              <span style={{ 
                background: 'rgba(0,0,0,0.5)', 
                padding: '4px 12px', 
                borderRadius: '12px', 
                fontSize: '0.8rem',
                color: 'var(--neon-green)'
              }}>
                {c.contributions} commits
              </span>
            </div>
          )) : (
            <p style={{ color: 'var(--text-secondary)' }}>A carregar contribuidores...</p>
          )}
        </div>
      </div>
    </div>
  );
}
