name: moz_utils
description: Funções de utilidade para Moçambique. Validação de NUIT, documentos e formatação de telefones.
version: 0.3.4
homepage: https://iradoweck.github.io/moz-utils/
repository: https://github.com/iradoweck/moz-utils/tree/main/dart
issue_tracker: https://github.com/iradoweck/moz-utils/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.24.0
