name: moz_utils
description: Utility functions for Mozambique — validation of NUIT, BI, documents, and phone number formatting.
version: 0.1.2
homepage: https://github.com/iradoweck/moz-utils/tree/main/dart
repository: https://github.com/iradoweck/moz-utils/tree/main/dart
issue_tracker: https://github.com/iradoweck/moz-utils/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  test: ^1.24.0
