[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "moz-utils"
version = "0.3.8"
description = "Funções de utilidade para Moçambique. Validação de NUIT, documentos e formatação de telefones."
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.8"
keywords = ["mozambique", "mz", "nuit", "dire", "postal-code", "cep", "m-pesa", "vodacom", "metical"]
authors = [
    {name = "Edmilson Muacigarro (@iradoweck)", email = "hello@edmilsonmuacigarro.com"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://iradoweck.github.io/moz-utils/"
Documentation = "https://iradoweck.github.io/moz-utils/#/docs/overview"
Repository = "https://github.com/iradoweck/moz-utils.git"
"Bug Tracker" = "https://github.com/iradoweck/moz-utils/issues"

[tool.pyright]
exclude = [
    "**/__pyrefly_virtual__/**",
    "**/*.md",
    "**/*.mdx"
]
ignore = [
    "**/__pyrefly_virtual__/**",
    "**/*.md",
    "**/*.mdx"
]
