[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "moz-utils"
version = "0.3.5"
description = "Funções de utilidade para Moçambique. Validação de NUIT, documentos e formatação de telefones."
readme = "README.md"
license = "AGPL-3.0-or-later"
requires-python = ">=3.8"
keywords = ["mozambique", "nuit", "bi", "mzn", "metical", "provincia", "distritos", "mocambique", "telecom", "validation"]
authors = [
  { name="Edmilson Muacigarro", email="contacto@edmilsonmuacigarro.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://iradoweck.github.io/moz-utils/"
Documentation = "https://iradoweck.github.io/moz-utils/#/docs/overview"
Repository = "https://github.com/iradoweck/moz-utils.git"
"Bug Tracker" = "https://github.com/iradoweck/moz-utils/issues"

[tool.pyright]
exclude = [
    "**/__pyrefly_virtual__/**",
    "**/*.md",
    "**/*.mdx"
]
ignore = [
    "**/__pyrefly_virtual__/**",
    "**/*.md",
    "**/*.mdx"
]
