name: Notify Private Monorepo

on:
  push:
    branches:
      - devlab

permissions:
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send update dispatch signal
        run: |
          curl -H "Authorization: token ${{ secrets.GH_PAT }}" \
               -H "Accept: application/vnd.github.v3+json" \
               -X POST \
               -d '{"event_type": "update_submodule"}' \
               https://api.github.com/repos/zedecks/nhonguista/dispatches
